config/routes.rb
Rails.application.routes.draw do 


  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  #get 'profile/new' => 'profile#index'

  resources :profile

  #get 'profile/:id' => 'profile#show'

  #post 'profile/:id' => 'profile#create'

  get 'services_location' =>'services_location#index'

  get 'services_list' => 'service_profile#index'


  root 'home#index'

  resources :services



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ServiceApp</title>
  <%= render :partial => 'shared/includes' %>
</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>">
      <img alt="Brand" src="">
    </a>
    <ul class="nav navbar-nav">
      <li><%= link_to "Find Services", services_location_path %></li>
      <li><%= link_to "My services List", services_list_path %></li>
      <li><%= link_to "Services", services_path %></li>
      <% if !user_signed_in? %>
      <li><%= link_to "Sign in with Facebook", omniauth_authorize_path(:user, :facebook) %></li>
      <% end %>
      </ul>
    <% if user_signed_in? %>
        <p class="navbar-text navbar-right">Signed in as <%=link_to current_user.name, edit_user_registration_path, class: "navbar-link"%>
          (<%= link_to 'Sign out', destroy_user_session_path,
                       :method => :delete %>)
        </p>

    <% else %>
        <p class="navbar-text navbar-right"><%= link_to 'Register', new_user_registration_path %> or
        <%= link_to 'Sign in', new_user_session_path %> </p>
    <% end %>
  </div>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container-fluid">

  <%= yield %>


</div>
</body>
</html>